-- =====================================================================
-- 068 — Sales Resources (admin-uploaded reference files for reps)
-- =====================================================================
-- Admins upload reference documents (PDF or HTML) that sales reps can
-- open from a new "Resources" tab in their portal. This migration adds:
--   * sales_resources            (one row per uploaded file)
--   * sales_resource_assignments (optional per-rep targeting)
--   * a private `sales-resources` storage bucket for the files
--   * RLS so reps only see resources visible to them; admins see all
--
-- Visibility model: a resource with NO assignment rows is shared with
-- every active rep. A resource with one or more assignment rows is
-- visible only to those reps. Archiving (is_active = false) hides a
-- resource from everyone.
--
-- Uploads/serving happen through service-role API routes (which bypass
-- RLS); the policies below keep direct PostgREST access correct.
-- RLS helper functions live in the `private` schema (migration 056).

CREATE TABLE IF NOT EXISTS sales_resources (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title         TEXT NOT NULL,
  description   TEXT,
  file_path     TEXT NOT NULL,              -- object path in the sales-resources bucket
  file_name     TEXT NOT NULL,              -- original filename, for display/download
  file_type     TEXT NOT NULL               -- MIME type of the stored file
                  CHECK (file_type IN ('application/pdf', 'text/html')),
  file_size     BIGINT NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,   -- false = archived (hidden from everyone)
  uploaded_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sales_resource_assignments (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id   UUID NOT NULL REFERENCES sales_resources(id) ON DELETE CASCADE,
  rep_id        UUID NOT NULL REFERENCES sales_reps(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (resource_id, rep_id)
);

CREATE INDEX IF NOT EXISTS idx_sales_resource_assignments_resource
  ON sales_resource_assignments(resource_id);
CREATE INDEX IF NOT EXISTS idx_sales_resource_assignments_rep
  ON sales_resource_assignments(rep_id);
CREATE INDEX IF NOT EXISTS idx_sales_resources_is_active
  ON sales_resources(is_active);

-- ------------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------------
ALTER TABLE sales_resources            ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_resource_assignments ENABLE ROW LEVEL SECURITY;

-- Reps read active resources that are either shared (no assignment rows)
-- or assigned to them. Admins read everything.
DROP POLICY IF EXISTS sales_resources_rep_select ON sales_resources;
CREATE POLICY sales_resources_rep_select ON sales_resources
  FOR SELECT TO authenticated
  USING (
    private.is_super_admin()
    OR (
      is_active = TRUE
      AND (
        NOT EXISTS (
          SELECT 1 FROM sales_resource_assignments a
          WHERE a.resource_id = sales_resources.id
        )
        OR EXISTS (
          SELECT 1 FROM sales_resource_assignments a
          WHERE a.resource_id = sales_resources.id
            AND a.rep_id = private.current_rep_id()
        )
      )
    )
  );

-- Only admins create / edit / archive resources.
DROP POLICY IF EXISTS sales_resources_admin_write ON sales_resources;
CREATE POLICY sales_resources_admin_write ON sales_resources
  FOR ALL TO authenticated
  USING (private.is_super_admin())
  WITH CHECK (private.is_super_admin());

-- Reps can see which resources are assigned to them; admins see all.
DROP POLICY IF EXISTS sales_resource_assignments_select ON sales_resource_assignments;
CREATE POLICY sales_resource_assignments_select ON sales_resource_assignments
  FOR SELECT TO authenticated
  USING (rep_id = private.current_rep_id() OR private.is_super_admin());

-- Only admins manage assignments.
DROP POLICY IF EXISTS sales_resource_assignments_admin_write ON sales_resource_assignments;
CREATE POLICY sales_resource_assignments_admin_write ON sales_resource_assignments
  FOR ALL TO authenticated
  USING (private.is_super_admin())
  WITH CHECK (private.is_super_admin());

-- ------------------------------------------------------------------
-- Storage bucket for the uploaded files (private).
-- ------------------------------------------------------------------
-- Files are served only via signed URLs generated by service-role API
-- routes, so reps never need direct bucket read access. Admin gets full
-- access for parity with the other private buckets.
INSERT INTO storage.buckets (id, name, public)
VALUES ('sales-resources', 'sales-resources', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "sales_resources_storage_admin_all" ON storage.objects;
CREATE POLICY "sales_resources_storage_admin_all" ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'sales-resources' AND private.is_super_admin())
  WITH CHECK (bucket_id = 'sales-resources' AND private.is_super_admin());
